### ISSUE TITLE
Restrict in which modes to run

### ISSUE THREAD

**Issue by antonmoiseev** [Farata/dart-template-cache-transformer#1]
Example:

``` yaml
transformers:
- template_cache_transformer:
    modes: [debug, release]
```

`debug` - run only with `pub serve`, `release` - run only with `pub build`
